import { Dictionary, DictionaryItem } from "./dictionary";
import { Grid } from "./grid";
import { GridBuilder } from "./grid-builder";

export * from './constraint';
export * from './dictionary';
export * from './grid';
export * from './grid-builder';

const dictionary = new Dictionary();
dictionary.words.add(new DictionaryItem('hello', 'plz define'));
dictionary.words.add(new DictionaryItem('there', 'plz define'));
dictionary.words.add(new DictionaryItem('eligible', 'plz define'));
dictionary.words.add(new DictionaryItem('entertain', 'plz define'));
dictionary.words.add(new DictionaryItem('my', 'plz define'));
dictionary.words.add(new DictionaryItem('name', 'plz define'));
dictionary.words.add(new DictionaryItem('is', 'plz define'));
dictionary.words.add(new DictionaryItem('remi', 'plz define'));
dictionary.words.add(new DictionaryItem('and', 'plz define'));
dictionary.words.add(new DictionaryItem('fun', 'plz define'));
dictionary.words.add(new DictionaryItem('boomer', 'plz define'));;
dictionary.words.add(new DictionaryItem('zoomer', 'plz define'));;
dictionary.words.add(new DictionaryItem('bike', 'plz define'));
dictionary.words.add(new DictionaryItem('bicycle', 'plz define'));
dictionary.words.add(new DictionaryItem('skateboard', 'plz define'));
dictionary.words.add(new DictionaryItem('board', 'plz define'));
dictionary.words.add(new DictionaryItem('boat', 'plz define'));
dictionary.words.add(new DictionaryItem('ball', 'plz define'));
dictionary.words.add(new DictionaryItem('bowl', 'plz define'));
dictionary.words.add(new DictionaryItem('bone', 'plz define'));
dictionary.words.add(new DictionaryItem('bile', 'plz define'));
dictionary.words.add(new DictionaryItem('rib', 'plz define'));
dictionary.words.add(new DictionaryItem('break', 'plz define'));
dictionary.words.add(new DictionaryItem('build', 'plz define'));
dictionary.words.add(new DictionaryItem('beast', 'plz define'));
dictionary.words.add(new DictionaryItem('power', 'plz define'));
dictionary.words.add(new DictionaryItem('broken', 'plz define'));;
dictionary.words.add(new DictionaryItem('cripple', 'plz define'));
dictionary.words.add(new DictionaryItem('table', 'plz define'));
dictionary.words.add(new DictionaryItem('door', 'plz define'));
dictionary.words.add(new DictionaryItem('fantasy', 'plz define'));
dictionary.words.add(new DictionaryItem('fantastic', 'plz define'));
dictionary.words.add(new DictionaryItem('under', 'plz define'));
dictionary.words.add(new DictionaryItem('crab', 'plz define'));
dictionary.words.add(new DictionaryItem('trash', 'plz define'));
dictionary.words.add(new DictionaryItem('bed', 'plz define'));
dictionary.words.add(new DictionaryItem('bid', 'plz define'));

const builder = new GridBuilder(new Grid(20, 20), dictionary);
builder.build();
console.log(builder.grid.toPrettyString());
