import { Dictionary } from "./dictionary";
import { Grid } from "./grid";
import { GridBuilder } from "./grid-builder";

const dictionary = new Dictionary();
dictionary.words.add('hello');
dictionary.words.add('there');
dictionary.words.add('eligible');
dictionary.words.add('entertain');
dictionary.words.add('my');
dictionary.words.add('name');
dictionary.words.add('is');
dictionary.words.add('remi');
dictionary.words.add('and');
dictionary.words.add('fun');
dictionary.words.add('boomer');
dictionary.words.add('zoomer');
dictionary.words.add('bike');
dictionary.words.add('bicycle');
dictionary.words.add('skateboard');
dictionary.words.add('board');
dictionary.words.add('boat');
dictionary.words.add('ball');
dictionary.words.add('bowl');
dictionary.words.add('bone');
dictionary.words.add('bile');
dictionary.words.add('rib');
dictionary.words.add('break');
dictionary.words.add('build');
dictionary.words.add('beast');
dictionary.words.add('power');
dictionary.words.add('broken');
dictionary.words.add('cripple');
dictionary.words.add('table');
dictionary.words.add('door');
dictionary.words.add('fantasy');
dictionary.words.add('fantastic');
dictionary.words.add('under');
dictionary.words.add('crab');
dictionary.words.add('trash');
dictionary.words.add('bed');
dictionary.words.add('bid');

const builder = new GridBuilder(new Grid(20, 20), dictionary);
builder.build();
console.log(builder.grid.toPrettyString());
